### ISSUE TITLE
Make Title & Descriptions for SEO

### ISSUE THREAD

**Issue by jMahapatra** [jMahapatra/jigyasa-ias#48]

**Comment by jMahapatra** [comment]
Make Title & Description for below pages

====> Important Pages <====
1. Home
2. Prelims Test Series
3. Mains Test Series
4. Interview
5. Current Affairs
6. Article
7. Answer Writing
8. Downloads
9. Weekly Magazine
10. Daily Study Programme
11. Essential Books Prelims
12. Daily Quiz
13. Contact
14. About Jigyasa
15. About UPSC

**Comment by jyotiranjanp424** [comment]
1.      Home

Titles:- jIgyASa - Top IAS UPSC academy New Delhi, IAS UPSC coaching,  UPSC free online tests

Description:- Jigyasa is one of the top IAS academy in New Delhi training aspirants for civil services examination. Providing top IAS UPSC coaching & UPSC free online tests.

2.	Preliminary test series

Title:- UPSC Preliminary test series, Prelims Master Test Series 2019

Description:- Jigyasa IAS offers paid and free UPSC Prelims Online Mock Tests. Our timed tests provide. IAS Prelims Master Test Series 2019: Unique Benefits. Check for more info JigyasaIAS

3.	Main test series

Title:- Main test series IAS UPSC

Description:- Jigyasa  is conducting Target programme for IAS UPSC  Main test series  2019. Also provides free daily test.

4.	Interview

Title:- IAS Interview, UPSC Civil Services Interview

Description:- IAS Interview is the most critical part of the IAS Exam. It can be help to get best services and also can be a deterrent in the final selection.

5.	Current Affairs

Title:- Current Affairs, UPSC IAS exam preparation

Description:- Current affairs that is needed for UPSC IAS exam preparation is updated every day (except Sundays) along with Question of the Day. 

6.	Article

Title:-  Latest Current Affairs Article, IAS UPSC Articles 

Description:- Jigyasa published  Latest Current Affairs Articles. Crisp news summaries and articles on current events about IAS and UPSC Exams.

7.	Answer Writing

Title:-  Answer writing UPSC, Answer writing practice for UPSC

Description:- Making a practice of Answer writing  for UPSC exam  is especially useful in managing the time limit set for the  exam and to write the best possible answer in the allotted time.

8.	Downloads

Title:- Download UPSC Syllabus 2019, Download UPSC  IAS Articles 

Description:- Download UPSC Prelims Syllabus 2019 for IAS, & other Civil Services Exams. Also Download UPSC IAS Articles and Govt. Welfare Schemes.

9.	Weekly Magazine

Title:-  Jigyasa Weekly  Magazine, Best Magazines for IAS Exam Preparation

Discription:- Best Magazines for IAS Exam Preparation  dedicated to the overall preparation of the civil service exam. Also download Jigyasa Weekly  Magazine.

10.	Daily Study Programme

Title:-  Daily Study Programme, daily study routine, plan to crack the IAS UPSC exam

Description:- Complete study plan for candidates appearing for IAS and UPSC exams. Follow this Jigyasa daily study plan. 

11.	Essential Books Prelims

Title:- essential books for upsc prelims, essential books for IAS

Description:- Essential books for UPSC prelims given here are recommended for UPSC IAS Exam. List of essential books  for IAS Prelims and books for UPSC IAS available here.

12.	Daily Quiz

Tiltle:- daily quiz for ias exam, daily current affairs quiz for upsc

Description:- Looking for top daily quiz for IAS UPSC exam ? Jigyasa provides daily quiz and current affairs for UPSC IAS exams.

13.	Contact

Title:- Best IAS UPSC Academy New Delhi, Contact us for top IAS UPSC Coaching

Description:- Jigyasa is one of the top IAS academy in New Delhi. Contact us for top IAS UPSC Coaching and training aspirants for civil services examination. 

14.	About Jigyasa

Titles:-  About Jigyasa, Jigyasa IAS Academy

Description:- We are a group of committed professionals having years of experience and expertise aiming to do the best we can for our nation by producing the best officers.

15.	About UPSC

Titles:- About UPSC,  UPSC Academy

Description:- The Union Public Service Commission is India's premier central recruiting agency.  Jigyasa is one of the top UPSC academy in New Delhi

**Comment by jyotiranjanp424** [comment]
7.	Answer Writing

Title:-  Answer writing upsc, Answer writing practice for upsc

Description:- To motivate and push serious UPSC civil services aspirants to practise answer writing for Mains Exam to improve their skills. Scan and upload the file. Get checked by our experts.

**Comment by jyotiranjanp424** [comment]
4.	Interview

Title:- IAS Mock  Interview, UPSC Civil Services Interview

Description:- IAS Interview is the most critical part of the IAS Exam. Jigyasa IAS conduct the mock IAS interview, so the aspirants will be helpful to get best services and also can be a deterrent in the final selection.

**Comment by jyotiranjanp424** [comment]
2.	Preliminary test series

Title:- UPSC Preliminary test series, Prelims Master Test Series 2019

Description:- Jigyasa IAS offers paid and free UPSC Prelims Online Mock Tests. Our timed tests provide IAS Prelims Master Test Series 2019: Unique Benefits.
